# Generated by Django 5.0.2 on 2024-02-15 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='files')),
                ('ver', models.CharField(max_length=5)),
                ('time_stamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
